---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check if /etc/cron.d/dehydrated exists
    stat:
      path: /etc/cron.d/dehydrated
    register: cron_file

  - name: Assert cron file exists
    ansible.builtin.assert:
      that: cron_file.stat.exists

  - name: Check if /usr/local/bin/dehy-check.sh exists
    stat:
      path: /usr/local/bin/dehy-check.sh
    register: check_file

  - name: Assert check helper file exists
    ansible.builtin.assert:
      that: check_file.stat.exists

  - name: Check if /usr/local/bin/dehy-wrap.sh exists
    stat:
      path: /usr/local/bin/dehy-wrap.sh
    register: wrap_file

  - name: Assert renew helper file exists
    ansible.builtin.assert:
      that: wrap_file.stat.exists
