---
name: Molecule

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: molecule
        uses: robertdebock/molecule-action@6.0.1
